### ISSUE TITLE
Using encoder latent vectors

### ISSUE THREAD

**Issue by armheb** [OmerKafri/StyleFusion#1]
Thanks for sharing your work, it's a great idea. I was trying to use e4e encoder to encode real images and use it with your model but the generated images don't match the real input image. 
This is the model result: 
![Screenshot from 2021-08-28 14-54-35](https://user-images.githubusercontent.com/18460769/131214898-c76a8f5d-bc89-4e68-9828-84ff3368b401.png)
 but the real image and encoded image:
![496bd940-1165-40de-ad84-529ff0c3edb9](https://user-images.githubusercontent.com/18460769/131214981-9594cfa8-d090-437a-b955-ff68d742aa08.png)

I appreciate your help.

**Comment by OmerKafri** [comment]
Hi, the results of e4e are in W+ space. try changing the 'latents_type' parameter from 'z' to 'w+'.
Let me know if it worked :)

**Comment by armheb** [comment]
Thanks for the tip, I checked the "w+" latents_type. the results improved but I still can't get the encoded image itself. 
Here is my result:
![Screenshot from 2021-08-28 22-25-13](https://user-images.githubusercontent.com/18460769/131226855-c19e603b-5db1-4d64-b88f-f0f82901b15d.png)

the encoded image is:
![download](https://user-images.githubusercontent.com/18460769/131226969-648ac397-85cc-4775-a4ce-38dd942725cc.png)

where is my problem? thanks again for your time.

**Comment by johndpope** [comment]
PTI has superior image inversion.  Albeit - I need help getting the PTI back into usable format. 
https://github.com/danielroich/PTI/issues/26

**Comment by OmerKafri** [comment]
Hi, I'm sorry for the late response.
I've done the same and acheived much better results. By design StyleFlusion should result with the same latent code if you use a single latent code as an input.
Maybe you are using a different pre-trained StyleGAN2 for StyleFusion and e4e?

Can you share a code that produces both the encoded image and the result of StyleFusion?

**Comment by armheb** [comment]
Thanks for the reply, I'm using the "stylegan2-ffhq-config-f.pt" pretrained StyleGAN2 model for both tasks. I used both the [colab](http://colab.research.google.com/github/omertov/encoder4editing/blob/main/notebooks/inference_playground.ipynb) notebook and inference script from the https://github.com/omertov/encoder4editing repo for producing the latent vectors and visualizing the results.
Here is my code for generating the images from the vectors using StyleFusion:

```
import torch
from matplotlib import pyplot as plt
from style_fusion_simple import StyleFusionSimple, tensor2im

ffhq_drawer = StyleFusionSimple("ffhq", "stylegan2-ffhq-config-f.pt", "weights/ffhq_weights.json")
latent=torch.load("latent.pt")
with torch.no_grad():
    img_t = ffhq_drawer.generate_img(latent[0],latents_type='w+')
tensor2im(img_t)
``` 
Here are the image and the latent vector I used: https://drive.google.com/drive/folders/1O8dEweWs1Ypc49JqALClXmqAYdNDIytT?usp=sharing
Thanks.

**Comment by armheb** [comment]
@OmerKafri  Can you please share the code you used for generating images from e4e latent codes using StyleFusion? that would be a great help. thanks.

**Comment by shayan-100** [comment]
@armheb @OmerKafri I have the same problem with the latent vectors. Can you please share any working code?

**Comment by armheb** [comment]
I'm still facing the same problem where I'm not able to reproduce the images from the latent vector using the above code.

**Comment by johndpope** [comment]
latents_type / from code - it's default is z. code above is referencing "w+"
is just a plain old "w" code able to get better results?

**Comment by armheb** [comment]
I got the latent codes from e4e encoder which is in w+, that's why I used "w+". I have tested "w" as well but the results stay the same. were you able to use latent vectors as input?

**Comment by johndpope** [comment]
I spent some time on https://github.com/danielroich/PTI/issues
unfortunately - haven't had time to play with this repo.

**Comment by OmerKafri** [comment]
Hi @armheb,

I debugged the issue and commited a fix to the generation of images out of a W+ latent code.
I mangaged to generate the image you've posted from the latent code that you've given, let me know if it works for you as well.

**Comment by armheb** [comment]
Thanks @OmerKafri, the problem is fixed now. I appreciate your help.
 Amazing job with StyleFusion.
I'll close this issue.
@shayan-100
