### ISSUE TITLE
Why are the indicators in the LatentBlender repeated for 10 times?

### ISSUE THREAD

**Issue by lastapple** [OmerKafri/StyleFusion#2]
Hi! I am impressed by your great work. I notice that you repeat the indicator in the LatentBlender 10 times. I know how the "(18+1)" comes but I don't understand why the "index_bits" is 10. Is this some kind of empirical parameters? 

![QQ截图20210903164612](https://user-images.githubusercontent.com/39229748/131979261-47d2c2cb-8544-441e-9fce-33db0d5da57c.png)

**Comment by OmerKafri** [comment]
Hi, thank you very much!
The initial tought was to give the indicators more weight. In practice I don't remember if we tried training without repeats or if we tried a different repeation amount.
I believe that not repeating the index bits will give simialr results, maybe slightly worse or less stable.

**Comment by lastapple** [comment]
OK,  I get it. Thanks for your reply!!
